### ISSUE TITLE
how are you

### ISSUE THREAD

**Issue by BoiZou** [kcct-fujimotolab/3DCNN#2]
While I running the code, the training process is keep working, but the acc/val_acc almost the same value after each iteration finished.
the result of the first to fifth just like this:
   - loss: 13.7778 - acc: 0.1451 -val_loss: 13.4866 - val_acc: 0.1633
   - loss: 13.8914 - acc: 0.1365 -val_loss: 13.6652 - val_acc: 0.1429
   - loss: 13.8352 - acc: 0.1416 -val_loss: 13.5962 - val_acc: 0.1565
   - loss: 13.8077 - acc: 0.1433 - val_loss: 13.4866 - val_acc: 0.1633
   - loss: 13.8842 - acc: 0.1382 -val_loss: 13.4866 - val_acc: 0.1633
What would be the reason? It's great appreciate that you give some advices. Thank you very much

**Comment by rysmarie** [comment]
Have you read [this issue](https://github.com/kcct-fujimotolab/3DCNN/issues/1) which has already been closed?

**Comment by rysmarie** [comment]
I'm sorry for not giving correct advice immediately.
This issue was caused by the ReLUs just before the max_pooling layers.
The weights of the dense layers were hardly updated because of them.
I've fixed this problem.
